receivers:
  hostmetrics:
    collection_interval: 5s  # Metrics collection frequency
    scrapers:
      cpu:
        metrics:
          system.cpu.time:
            enabled: true
          system.cpu.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.usage:
            enabled: true
          system.memory.utilization:
            enabled: true
      disk:
        metrics:
          system.disk.io:
            enabled: true
          system.disk.operations:
            enabled: true
      filesystem:
        metrics:
          system.filesystem.usage:
            enabled: true
          system.filesystem.utilization:
            enabled: true
      network:
        metrics:
          system.network.connections:
            enabled: true
          system.network.io:
            enabled: true
      load:
      processes:
        metrics:
          system.processes.created:
            enabled: true
          system.processes.count:
            enabled: true
  filelog:
    include: ${LOG_FILE_PATH}  # path to the log file

  # journald:
  #     directory: /run/log/journal
  #     units:
  #       - ssh
  #       - kubelet
  #       - docker
  #       - containerd
  #     priority: info

processors:
  resourcedetection:
    detectors: ["env", "system"]
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  # otlp:
  #   endpoint: "localhost:4317"
  #   tls:
  #     insecure: true
  otlphttp:
    endpoint:  ${SIGNOZ_CLUSTER_ENDPOINT}  # "http://localhost:4318" or "https://metrics.openmined.org"
    # tls:
    #   insecure: true
  # file/no_rotation:
  #     path: ./otel-collector.json

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [otlphttp]
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [otlphttp]