receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:5555  # configure the app to send telemetry data to this endpoint
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.frequency:
            enabled: true
          system.cpu.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      network:
        metrics:
          system.network.conntrack.count:
            enabled: true
      load:
      disk:
      filesystem:
      processes:
  filelog:
    include: ${LOG_FILE_PATH}  # path to the log file

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  resourcedetection:
    detectors: ["system"]
    timeout: 2s
    system:
      hostname_sources: ["os"]
  resource:
    attributes:
      - key: syftbox.server.env
        value: stage
        action: upsert

exporters:
  otlp:
    endpoint: http://localhost:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, resource, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resourcedetection, resource, batch]
      exporters: [otlp]
    # logs:
    #   receivers: [otlp]
    #   processors: [resourcedetection, resource, batch]
    #   exporters: [otlp]
    logs:
      receivers: [filelog]
      processors: [resourcedetection, resource, batch]
      exporters: [otlp]